### PR TITLE
Rule details page

### PR DESCRIPTION
**Pull request by edmundoa**
Editing rules in a modal is far from optimal, so I decided to move the form to its own page. This gives us some advantages:

- Display rule examples and functions to help users writing their own rules
- Link to the details page from anywhere, as we can point to this page with the ID, not needing to load the rules and create modals for each one of them
- The editor errors will show up in the right place

What do you think? Yay or nay?

### CODE REVIEW

**Comment by kroepke** [comment]
¡Me gusta mucho!

I can take care of exposing the function descriptors (or can help you do it)

**Comment by edmundoa** [comment]
Cool! I'm not sure if we should add all functions, there are too many and the column looks huge, but at least we can take a look :+1:

**Comment by kroepke** [comment]
We could eventually make it context-aware or at least searchable. But for now we can leave it like this, too, I think.

**Comment by edmundoa** [comment]
True, we can try that. I was thinking of categorizing them somehow as well, but I couldn't come up with some sensible categories, that's why I just kept the "most common" ones.

**Comment by kroepke** [comment]
lgtm

**Pull request merged**
